if(!window.qx)window.qx={};
qx.Bootstrap={genericToString:function(){return"[Class "+this.classname+"]"},createNamespace:function(a,b){for(var c=a.split("."),d=window,e=c[0],f=0,g=c.length-1;f<g;f++,e=c[f])d=d[e]?d[e]:d[e]={};d[e]=b;return e},setDisplayName:function(a,b,c){a.displayName=b+"."+c+"()"},setDisplayNames:function(a,b){for(var c in a){var d=a[c];if(d instanceof Function)d.displayName=b+"."+c+"()"}},define:function(a,b){b||(b={statics:{}});var c,d=null;qx.Bootstrap.setDisplayNames(b.statics,a);if(b.members||b.extend){qx.Bootstrap.setDisplayNames(b.members,
a+".prototype");c=b.construct||new Function;b.extend&&this.extendClass(c,c,b.extend,a,e);for(var d=b.statics||{},e=0,f=qx.Bootstrap.getKeys(d),g=f.length;e<g;e++){var h=f[e];c[h]=d[h]}for(var d=c.prototype,i=b.members||{},e=0,f=qx.Bootstrap.getKeys(i),g=f.length;e<g;e++)h=f[e],d[h]=i[h]}else c=b.statics||{};var e=this.createNamespace(a,c);c.name=c.classname=a;c.basename=e;c.$$type="Class";if(!c.hasOwnProperty("toString"))c.toString=this.genericToString;b.defer&&b.defer(c,d);qx.Bootstrap.$$registry[a]=
b.statics;return c}};
qx.Bootstrap.define("qx.Bootstrap",{statics:{LOADSTART:qx.$$start||new Date,DEBUG:function(){var a=true;qx.$$environment&&qx.$$environment["qx.debug"]===false&&(a=false);return a}(),getEnvironmentSetting:function(a){if(qx.$$environment)return qx.$$environment[a]},setEnvironmentSetting:function(a,b){if(!qx.$$environment)qx.$$environment={};qx.$$environment[a]===void 0&&(qx.$$environment[a]=b)},createNamespace:qx.Bootstrap.createNamespace,define:qx.Bootstrap.define,setDisplayName:qx.Bootstrap.setDisplayName,setDisplayNames:qx.Bootstrap.setDisplayNames,
genericToString:qx.Bootstrap.genericToString,extendClass:function(a,b,c,d,e){var f=c.prototype,g=new Function;g.prototype=f;f=new g;a.prototype=f;f.name=f.classname=d;f.basename=e;b.base=a.superclass=c;b.self=a.constructor=f.constructor=a},getByName:function(a){return qx.Bootstrap.$$registry[a]},$$registry:{},objectGetLength:{count:function(a){return a.__count__},"default":function(a){var b=0,c;for(c in a)b++;return b}}[{}.__count__==0?"count":"default"],objectMergeWith:function(a,b,c){c===void 0&&
(c=true);for(var d in b)if(c||a[d]===void 0)a[d]=b[d];return a},__shadowedKeys:"isPrototypeOf,hasOwnProperty,toLocaleString,toString,valueOf,constructor".split(","),getKeys:{ES5:Object.keys,BROKEN_IE:function(a){var b=[],c=Object.prototype.hasOwnProperty,d;for(d in a)c.call(a,d)&&b.push(d);d=0;for(var e=qx.Bootstrap.__shadowedKeys,f=e.length;d<f;d++)c.call(a,e[d])&&b.push(e[d]);return b},"default":function(a){var b=[],c=Object.prototype.hasOwnProperty,d;for(d in a)c.call(a,d)&&b.push(d);return b}}[typeof Object.keys==
"function"?"ES5":function(){for(var a in{toString:1})return a}()!=="toString"?"BROKEN_IE":"default"],getKeysAsString:function(a){a=qx.Bootstrap.getKeys(a);return a.length==0?"":'"'+a.join('", "')+'"'},__classToTypeMap:{"[object String]":"String","[object Array]":"Array","[object Object]":"Object","[object RegExp]":"RegExp","[object Number]":"Number","[object Boolean]":"Boolean","[object Date]":"Date","[object Function]":"Function","[object Error]":"Error"},bind:function(a,b,c){var d=Array.prototype.slice.call(arguments,
2,arguments.length);return function(){var c=Array.prototype.slice.call(arguments,0,arguments.length);return a.apply(b,d.concat(c))}},firstUp:function(a){return a.charAt(0).toUpperCase()+a.substr(1)},firstLow:function(a){return a.charAt(0).toLowerCase()+a.substr(1)},getClass:function(a){a=Object.prototype.toString.call(a);return qx.Bootstrap.__classToTypeMap[a]||a.slice(8,-1)},isString:function(a){return a!==null&&(typeof a==="string"||qx.Bootstrap.getClass(a)=="String"||a instanceof String||!!a&&
!!a.$$isString)},isArray:function(a){return a!==null&&(a instanceof Array||a&&qx.data&&qx.data.IListData&&qx.Bootstrap.hasInterface(a.constructor,qx.data.IListData)||qx.Bootstrap.getClass(a)=="Array"||!!a&&!!a.$$isArray)},isObject:function(a){return a!==void 0&&a!==null&&qx.Bootstrap.getClass(a)=="Object"},isFunction:function(a){return qx.Bootstrap.getClass(a)=="Function"},classIsDefined:function(a){return qx.Bootstrap.getByName(a)!==void 0},getPropertyDefinition:function(a,b){for(;a;){if(a.$$properties&&
a.$$properties[b])return a.$$properties[b];a=a.superclass}return null},hasProperty:function(a,b){return!!qx.Bootstrap.getPropertyDefinition(a,b)},getEventType:function(a,b){for(a=a.constructor;a.superclass;){if(a.$$events&&a.$$events[b]!==void 0)return a.$$events[b];a=a.superclass}return null},supportsEvent:function(a,b){return!!qx.Bootstrap.getEventType(a,b)},getByInterface:function(a,b){for(var c,d,e;a;){if(a.$$implements){c=a.$$flatImplements;for(d=0,e=c.length;d<e;d++)if(c[d]===b)return a}a=a.superclass}return null},
hasInterface:function(a,b){return!!qx.Bootstrap.getByInterface(a,b)},getMixins:function(a){for(var b=[];a;)a.$$includes&&b.push.apply(b,a.$$flatIncludes),a=a.superclass;return b},$$logs:[],debug:function(a,b){qx.Bootstrap.$$logs.push(["debug",arguments])},info:function(a,b){qx.Bootstrap.$$logs.push(["info",arguments])},warn:function(a,b){qx.Bootstrap.$$logs.push(["warn",arguments])},error:function(a,b){qx.Bootstrap.$$logs.push(["error",arguments])},trace:function(){}}});